name: Paradox Link Check

on:
  workflow_dispatch:
  schedule:
    - cron: '30 19 * * *' # run at 1:00 AM IST

jobs:
  paradox:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2
      - name: Paradox Validate Links
        run: sbtn docs/paradoxValidateLinks

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-dev
