name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      CSW_VERSION: "3.0.0-M1"
      ESW_VERSION: "0.2.0-M1"
      ESW_BACKEND_TEMPLATE_VERSION: "0.1.0-M1"
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: adopt@1.11
      - uses: coursier/cache-action@v3

      - uses: actions/setup-node@v1
        with:
          node-version: "13.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Redis
        run: sudo apt-get install redis-server

      - name: Install CS native
        run: |
          curl -fLo cs https://git.io/coursier-cli-linux &&
          chmod +x cs
          sudo mv cs /usr/local/bin
          cs install --add-channel https://raw.githubusercontent.com/tmtsoftware/osw-apps/master/apps.json

      - name: Install Kotlin
        run: |
          curl -s https://get.sdkman.io | bash
          source "/home/runner/.sdkman/bin/sdkman-init.sh"
          sdk install kotlin
          sudo ln -s $(which kotlinc) /usr/local/bin/kotlinc

      - run: npm install -g junit-merge
      - run: npm install -g junit-viewer

      - name: Build
        run: |
          sbt scalafmtCheck
          sbt clean makeSite
          sbt -DenableFatalWarnings=true ';set every Seq(scalafmtOnCompile := false); test:compile; multi-jvm:compile;'

      - name: Tests
        run: sbt -Dakka.actor.serialize-messages=on -DenableCoverage=true -DgenerateStoryReport=true test:test

      - name: Coverage Report
        run: |
          sbt -DenableCoverage=true coverageReport
          sbt coverageAggregate

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v1
        with:
          name: Coverage Report
          path: target/scala-2.13/scoverage-report

      - name: Delete js targets
        continue-on-error: true
        run: find . -type d -regex ".*js/target.*" | xargs rm -rf

      - name: Multi-Jvm Tests
        run: sbt -DgenerateStoryReport=true esw-integration-test/multi-jvm:test

      - name: Generate RTM
        if: always()
        continue-on-error: true
        run: |
          ./scripts/coursier launch --channel https://raw.githubusercontent.com/tmtsoftware/osw-apps/master/apps.json rtm:33b2359b23 -- target/RTM/testStoryMapping.txt tools/RTM/storyRequirementMapping.csv target/RTM/testRequirementsMapping.txt

      - name: Upload RTM
        if: always()
        continue-on-error: true
        uses: actions/upload-artifact@v1
        with:
          name: RTM
          path: target/RTM

      - name: Github Release
        run: sbt -Dprod.publish=true githubRelease
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}

      - name: Docs Publish
        run: |
          echo 'echo $RELEASE_TOKEN' > /tmp/.git-askpass
          chmod +x /tmp/.git-askpass
          git config --global user.email "actions@github.com"
          git config --global user.name "Github Action"
          sbt -Dprod.publish=true clean ghpagesPushSite
        env:
          RELEASE_TOKEN: ${{ secrets.RELEASE_TOKEN }}
          GIT_ASKPASS: /tmp/.git-askpass

      - name: Notify slack
        if: always()
        continue-on-error: true
        uses: kpritam/slack-job-status-action@v1
        with:
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel: ci-release
